feat: sorted rooms.json by name
cabinweekend/jitsi-party pull request #11
Opened 2022-07-06 05:48 UTC by lamontano

Let me know if you have any questions or want me to make any changes.

2022-07-07 05:54 UTC, hndrewaall requested changes
Thanks for helping out! 

You resolved the conflicts in the wrong direction (you effectively reverted the upstream changes, see the Files changed view). In this particular case, because we change these every week, this doesn't matter much. But it'd be good practice to try to get this so that it's just sorting the existing config in master.

2022-07-07 05:55 UTC, hndrewaall commented on authbot/authbot.py
> +    "temple-6-21-22-pride-vice-or-virtue": "Temple21June22",
For example, you shouldn't be changing this file at all

2022-07-10 20:37 UTC, rene-grigory commented
I reviewed this with Luis and he will be creating a new PR once he has his changes corrected. There was a little confusion with the branches and forks, but I think he's on the right track now. 

@hndrewaall : this is was an exercise to get Luis used to our process and Ada felt that having the temple rooms sorted would be nice for the caretakers since they don't typically mess with the room order in the temple.

2022-07-11 00:46 UTC, closed without merging

2022-07-11 00:46 UTC, lamontano commented
Closing this since this has been corrected in https://github.com/cabinweekend/jitsi-party/pull/12